### ISSUE TITLE
Fixing the library version to comply with rust toolchain

### ISSUE THREAD

**Issue by anupsv** [axiom-crypto/halo2-scaffold#14]
This project currently has a hard time building at the specified nightly version. Newer versions also have some sort of similar issues but i didn't bother updating to newer version. Just worked on updating the lib version to comply with the rust-toolchain version used.

The following updates worked:
```
cargo update -p clap@4.4.1 --precise 4.3.19
cargo update -p clap_lex@0.5.1 --precise 0.5.0
```

Hopefully this helps someone as well.

**Comment by ryanycw** [comment]
Thank you for the updates! This solved my issue.

**Comment by jonathanpwang** [comment]
https://github.com/axiom-crypto/halo2-scaffold/pull/25
